(setq some-hash-table (make-hash-table))
(set-hash some-hash-table 5 "Hello")
(set-hash some-hash-table "apple" 9)
(set-hash some-hash-table "orange" "cool")
(set-hash some-hash-table "something" nil)
(print "Value at key 5 in hash table: " (get-hash some-hash-table 5))
(print "Value at key orange in hash table: " (get-hash some-hash-table "orange"))
(print "Value at key 8 in hash table: " (get-hash some-hash-table 8))
(print "Resulting hashtable: " some-hash-table)
